### ISSUE TITLE
Ph Value

### ISSUE THREAD

**Issue by Simonv92** [tdragon/reef-pi-hass-custom#22]
Hi,
I'm testing the Reef-Pi integration,
Everything works fine exept for the analog sensor reading: 
I'm using a Ph Sesor and if I calibrate the probe in Reef-Pi I have the right value, but in Home Assistant I only have the raw ADC value.
How can I solve that?
Thank you very much!
Best regards

Simone

**Comment by danmrossi** [comment]
Hi Simone, Fellow user of this integration here. Thought id see if i can be of any help :)

What version of reef-pi are you using? Same Goes for Home Assistant and the addon?

The addon was fixed to work with v6.0 of reef-pi. If you are running one of the older versions of reef-pi you might have to try one of the older versions of the integration.

The HA Addon gets it's PH Readings from API http://reefpi-ip-address/api/phprobes/1/read - Where number "1" is the id of your PH Probe - I believe it increments up if you have multiple probes and / or have deleted and recreated.

That API page if you go to it on your system is the current reading of the PH Probe from the reef-pi - That is the same value as what shows up in HA.

I Believe there are outstanding issues with reef-pi 5.3/6.0 with the PH Graph in reef-pi GUI but the coder there hasn't gotten around to fixing it (Ranjib has acknowledged it as a fault although) since i reported it in December. 

Regards

Daniel

**Comment by danmrossi** [comment]
Meant to add as well i believe this integration was getting its readings originally from http://reef-pi-ip-address/api/phprobes/1/readings - Which brings up the whole history of your readings and due to the reef-pi DB layout issue was causing some issues in getting and reporting the correct reading.
